"""initial schema

Revision ID: 72f32ab86a41
Revises: 
Create Date: 2026-05-29 21:14:46.748270
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '72f32ab86a41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('human', 'agent', 'skill', 'llm', 'tool', 'dataset', 'workflow', 'organization', 'community', name='entitytype', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', name='entitystatus', native_enum=False, length=32), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_index('ix_entities_status', 'entities', ['status'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('maintainer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['maintainer_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('org_type', sa.String(length=64), nullable=False),
    sa.Column('governance_proxy_id', sa.String(length=36), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['governance_proxy_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_table('reputation_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reputation_scores_entity_id', 'reputation_scores', ['entity_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('maintainer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['maintainer_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sponsor_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'completed', 'closed', name='taskstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('user_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_provider_identity')
    )
    op.create_index('ix_user_accounts_entity_id', 'user_accounts', ['entity_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('cp_balance', sa.Float(), nullable=False),
    sa.Column('ai_credits', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('credits_spent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_usage_logs_created_at', 'ai_usage_logs', ['created_at'], unique=False)
    op.create_index('ix_ai_usage_logs_entity_id', 'ai_usage_logs', ['entity_id'], unique=False)
    op.create_table('contribution_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('primary_entity_id', sa.String(length=36), nullable=False),
    sa.Column('contribution_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'ai_verified', 'approved', 'rejected', name='contributionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contribution_events_created_at', 'contribution_events', ['created_at'], unique=False)
    op.create_index('ix_contribution_events_status', 'contribution_events', ['status'], unique=False)
    op.create_index('ix_contribution_events_task_id', 'contribution_events', ['task_id'], unique=False)
    op.create_table('ai_verifier_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribution_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('creator', 'executor', 'reviewer', 'verifier', 'tool_provider', 'data_provider', 'skill_provider', 'model_provider', 'coordinator', 'sponsor', name='participantrole', native_enum=False, length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution_events.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contribution_participants_contribution_id', 'contribution_participants', ['contribution_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('credit_type', sa.Enum('cp', 'ai_credits', name='credittype', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution_events.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_transactions_wallet_id', 'credit_transactions', ['wallet_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution_events.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invocation_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('initiator_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('contribution_id', sa.String(length=36), nullable=True),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('started', 'completed', 'failed', name='invocationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution_events.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invocation_traces_initiator_id', 'invocation_traces', ['initiator_id'], unique=False)
    op.create_table('ledger_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_records_created_at', 'ledger_records', ['created_at'], unique=False)
    op.create_table('invocation_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['invocation_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invocation_steps_trace_id', 'invocation_steps', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invocation_steps_trace_id', table_name='invocation_steps')
    op.drop_table('invocation_steps')
    op.drop_index('ix_ledger_records_created_at', table_name='ledger_records')
    op.drop_table('ledger_records')
    op.drop_index('ix_invocation_traces_initiator_id', table_name='invocation_traces')
    op.drop_table('invocation_traces')
    op.drop_table('human_reviews')
    op.drop_index('ix_credit_transactions_wallet_id', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('ix_contribution_participants_contribution_id', table_name='contribution_participants')
    op.drop_table('contribution_participants')
    op.drop_table('ai_verifier_results')
    op.drop_index('ix_contribution_events_task_id', table_name='contribution_events')
    op.drop_index('ix_contribution_events_status', table_name='contribution_events')
    op.drop_index('ix_contribution_events_created_at', table_name='contribution_events')
    op.drop_table('contribution_events')
    op.drop_index('ix_ai_usage_logs_entity_id', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_created_at', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_table('wallets')
    op.drop_index('ix_user_accounts_entity_id', table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('skills')
    op.drop_index('ix_reputation_scores_entity_id', table_name='reputation_scores')
    op.drop_table('reputation_scores')
    op.drop_table('organizations')
    op.drop_table('agents')
    op.drop_index('ix_entities_status', table_name='entities')
    op.drop_index('ix_entities_entity_type', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
